/**
 * The bundled optical identity codes, and the arithmetic that justifies them.
 *
 * A code used for identity has one job: correlate strongly with itself and
 * weakly with everything else, including with *shifted copies of itself*, since
 * a receiver that does not know the transmitter's phase has to search over
 * phase and will happily accept a shift if the code permits one.
 *
 * Maximum-length sequences have exactly that property. An m-sequence of length
 * `2^n - 1` generated by a primitive polynomial has periodic autocorrelation
 * `N` at zero shift and `-1` at every other shift — the flattest off-peak a
 * binary sequence of that length can have. That is a stated, checkable
 * property, and `code-library.test.ts` checks it rather than trusting it.
 *
 * Nothing here encodes a simulator entity, an index or an id. A code is a
 * signalling pattern that a terminal emits and another terminal expects; which
 * physical object happens to be carrying it is exactly the question the tracker
 * has to answer from pixels.
 *
 * See docs/BEACON_IDENTITY.md.
 */

import type { CodeSymbol } from './code-waveform';

/**
 * Generates a maximum-length sequence from a primitive polynomial.
 *
 * Fibonacci LFSR: the taps name the register stages that are exclusive-ored to
 * form the feedback bit. For a primitive polynomial of degree `n` the register
 * visits all `2^n - 1` non-zero states before repeating, which is what makes
 * the output sequence maximum length.
 *
 * @param degree  register length `n`; the sequence is `2^n - 1` symbols
 * @param taps    1-based stage indices, including `degree`
 * @throws {RangeError} when the register would be degenerate
 */
export function maximumLengthSequence(degree: number, taps: readonly number[]): CodeSymbol[] {
  if (!Number.isInteger(degree) || degree < 2 || degree > 16) {
    throw new RangeError(`LFSR degree must be an integer in [2, 16], received ${String(degree)}`);
  }
  if (taps.length === 0 || taps.some((tap) => !Number.isInteger(tap) || tap < 1 || tap > degree)) {
    throw new RangeError(`LFSR taps must be integers in [1, ${String(degree)}]`);
  }

  // All ones is as good a non-zero seed as any: every non-zero state lies on
  // the same cycle, so the seed selects a phase and nothing else.
  const register = new Array<number>(degree).fill(1);
  const length = 2 ** degree - 1;
  const sequence: CodeSymbol[] = [];

  for (let step = 0; step < length; step += 1) {
    // The output is the last stage, shifted out.
    sequence.push(register[degree - 1] === 1 ? 1 : 0);
    let feedback = 0;
    for (const tap of taps) feedback ^= register[tap - 1]!;
    register.copyWithin(1, 0, degree - 1);
    register[0] = feedback;
  }

  return sequence;
}

/**
 * Periodic cross-correlation of two equal-length binary sequences at `shift`.
 *
 * Symbols are mapped `0 -> -1`, `1 -> +1` before summing, which is what makes
 * the m-sequence off-peak value `-1` rather than something that depends on how
 * many ones the sequence happens to contain. The result is an integer in
 * `[-N, N]`.
 *
 * @throws {RangeError} when the sequences differ in length or are empty
 */
export function periodicCorrelation(
  a: readonly CodeSymbol[],
  b: readonly CodeSymbol[],
  shift: number,
): number {
  if (a.length === 0 || a.length !== b.length) {
    throw new RangeError('Periodic correlation needs two non-empty sequences of equal length');
  }
  const length = a.length;
  let total = 0;
  for (let index = 0; index < length; index += 1) {
    const shifted = (((index + shift) % length) + length) % length;
    total += (a[index] === 1 ? 1 : -1) * (b[shifted] === 1 ? 1 : -1);
  }
  return total;
}

/** The largest magnitude of the correlation between two codes over all shifts. */
export function peakCrossCorrelation(a: readonly CodeSymbol[], b: readonly CodeSymbol[]): number {
  let peak = 0;
  for (let shift = 0; shift < a.length; shift += 1) {
    peak = Math.max(peak, Math.abs(periodicCorrelation(a, b, shift)));
  }
  return peak;
}

/** The largest off-peak magnitude of a code's correlation with itself. */
export function peakSidelobe(code: readonly CodeSymbol[]): number {
  let peak = 0;
  for (let shift = 1; shift < code.length; shift += 1) {
    peak = Math.max(peak, Math.abs(periodicCorrelation(code, code, shift)));
  }
  return peak;
}

/** A cyclic rotation of a sequence. */
export function rotate(code: readonly CodeSymbol[], shift: number): CodeSymbol[] {
  const length = code.length;
  return code.map((_, index) => code[(((index + shift) % length) + length) % length]!);
}

/**
 * The two distinct length-15 maximum-length sequences.
 *
 * Degree 4 has exactly two primitive polynomials, `x^4 + x + 1` and
 * `x^4 + x^3 + 1`, so there are exactly two m-sequences of length 15 up to
 * rotation. That is the whole supply at this length, and it is worth stating
 * plainly: a system needing many mutually distinguishable codes needs longer
 * ones, and this project's default camera timing does not have room for them.
 */
export const CODE_A: readonly CodeSymbol[] = Object.freeze(maximumLengthSequence(4, [4, 1]));
export const CODE_B: readonly CodeSymbol[] = Object.freeze(maximumLengthSequence(4, [4, 3]));

/**
 * A rotation of {@link CODE_A} by four symbols.
 *
 * Deliberately a *bad* code to try to tell apart from `CODE_A`: a receiver that
 * searches over phase — which it must, not knowing the transmitter's clock —
 * sees a rotation of a code as that same code at a different phase, and cannot
 * distinguish them at all. It is here as a negative control, to make the
 * limitation demonstrable instead of merely admitted.
 */
export const CODE_A_SHIFTED: readonly CodeSymbol[] = Object.freeze(rotate(CODE_A, 4));

/** The bundled codes, by name. */
export const CODE_LIBRARY = {
  /** The reference target code. */
  TARGET_CODE_A: CODE_A,
  /** A genuinely different code, for a decoy that signals something else. */
  DECOY_CODE_B: CODE_B,
  /** A rotation of the target code: indistinguishable under a phase search. */
  AMBIGUOUS_CODE_A_SHIFTED: CODE_A_SHIFTED,
} as const;

export type CodeName = keyof typeof CODE_LIBRARY;
